# Generated by Django 5.2.6 on 2025-09-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_article_article22'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article22',
            new_name='Article',
        ),
    ]
