# Generated by Django 5.2.4 on 2025-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='식당 설명'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='식당 전화번호'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(verbose_name='식당 주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='식당 이름'),
        ),
    ]
